### ISSUE TITLE
[Support] 

### ISSUE THREAD

**Issue by m1e1w1** [aetaric/checkrr#87] opened 2024-01-01 09:45 UTC
Not a bug, but first issue reported remains the same. No clear direction on getting checkrr to run with the minimal (not enough detail) setup.

author replied that i was not using absolute paths for the configuration file, or relative path for the configuration.

here is my configuration file:

checkrr:
  checkpath: 
(removed)
  database: ./checkrr.db
  debug: true
  csvfile: "./badfiles.csv"
  logfile: "./checkrr.log"
  logjson: false
  cron: "@daily"
  ignorehidden: true
  
Location of checkrr:
/home/user/docker/checkrr

Both database and yaml file are inside checkrr folder.

path should be set correctly here? or do i need to specifically write out /home/user/checkrr/checkrr.db and checkrr.yaml?

I did try running with full path, same issue as original post, not found. wont run.

thank you for taking a look.

**Comment by aetaric** [comment] 2024-01-11 07:50
You should escape your config with triple backticks (```) on both sides of the config on their own line. (see [Creating and Highlighting Code Blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) from GitHub's documentation)

The config file is in YAML, so you ***MUST*** use spaces. Tabs are an illegal character in YAML, so if you've even touched the tab key, or used something that could have put a tab instead of a space, you should start over fresh.

Outside of that, what error are you getting? I can run checkrr without issue, both release and the dev build:

```
➜  checkrr git:(main) ./checkrr -c test-noarr.yaml 

            _|                               _|
   _|_|_|   _|_|_|       _|_|       _|_|_|   _|  _|     _|  _|_|   _|  _|_|
 _|         _|    _|   _|_|_|_|   _|         _|_|       _|_|       _|_|
 _|         _|    _|   _|         _|         _|  _|     _|         _|
   _|_|_|   _|    _|     _|_|_|     _|_|_|   _|    _|   _|         _|
Checkrr version development
 Commit: 
 Built On: 
 Built By: 
INFO[0000] Using config file: test-noarr.yaml           
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /api/files/bad            --> github.com/aetaric/checkrr/webserver.getBadFiles (4 handlers)
[GIN-debug] POST   /api/files/bad            --> github.com/aetaric/checkrr/webserver.deleteBadFiles (4 handlers)
[GIN-debug] GET    /api/stats/current        --> github.com/aetaric/checkrr/webserver.getCurrentStats (4 handlers)
[GIN-debug] GET    /api/stats/historical     --> github.com/aetaric/checkrr/webserver.getHistoricalStats (4 handlers)
[GIN-debug] GET    /api/schedule             --> github.com/aetaric/checkrr/webserver.getSchedule (4 handlers)
[GIN-debug] POST   /api/run                  --> github.com/aetaric/checkrr/webserver.runCheckrr (4 handlers)
INFO[0000] Next Run: 2024-01-11 00:47:00 -0700 MST      
[GIN-debug] Listening and serving HTTP on :8585
```

```
➜  checkrr git:(main) dist/checkrr_darwin_arm64/checkrr -c test-noarr.yaml 

            _|                               _|
   _|_|_|   _|_|_|       _|_|       _|_|_|   _|  _|     _|  _|_|   _|  _|_|
 _|         _|    _|   _|_|_|_|   _|         _|_|       _|_|       _|_|
 _|         _|    _|   _|         _|         _|  _|     _|         _|
   _|_|_|   _|    _|     _|_|_|     _|_|_|   _|    _|   _|         _|
Checkrr version 3.2.2
 Commit: 5b141e66750e9d2aad55b9855c545a7256ea2ed4
 Built On: 2023-12-12T07:28:28Z
 Built By: goreleaser
INFO[0000] Using config file: test-noarr.yaml           
INFO[0000] Next Run: 2024-01-11 00:47:00 -0700 MST      
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /api/files/bad            --> github.com/aetaric/checkrr/webserver.getBadFiles (4 handlers)
[GIN-debug] POST   /api/files/bad            --> github.com/aetaric/checkrr/webserver.deleteBadFiles (4 handlers)
[GIN-debug] GET    /api/stats/current        --> github.com/aetaric/checkrr/webserver.getCurrentStats (4 handlers)
[GIN-debug] GET    /api/stats/historical     --> github.com/aetaric/checkrr/webserver.getHistoricalStats (4 handlers)
[GIN-debug] GET    /api/schedule             --> github.com/aetaric/checkrr/webserver.getSchedule (4 handlers)
[GIN-debug] POST   /api/run                  --> github.com/aetaric/checkrr/webserver.runCheckrr (4 handlers)
[GIN-debug] Listening and serving HTTP on :8585
```

**Comment by aetaric** [comment] 2024-01-27 17:20
Hello, 

I cannot reproduce this with the information provided so I will close this issue. If you still need help, please comment with the requested information and I'll reopen it.

**Closed by aetaric** 2024-01-27 17:20 UTC
Labels: question, support
